//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolPortalEntities : DbContext
    {
        public SchoolPortalEntities()
            : base("name=SchoolPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Algebra_grades> Algebra_grades { get; set; }
        public virtual DbSet<Geometry_grades> Geometry_grades { get; set; }
        public virtual DbSet<Grades_Students> Grades_Students { get; set; }
        public virtual DbSet<Literature_grades> Literature_grades { get; set; }
        public virtual DbSet<Physical_education_grades> Physical_education_grades { get; set; }
        public virtual DbSet<Russian_language_grades> Russian_language_grades { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Secret_key> Secret_key { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
        public virtual DbSet<Work_grades> Work_grades { get; set; }
    }
}
