//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.Algebra_grades = new HashSet<Algebra_grades>();
            this.Geometry_grades = new HashSet<Geometry_grades>();
            this.Grades_Students = new HashSet<Grades_Students>();
            this.Literature_grades = new HashSet<Literature_grades>();
            this.Physical_education_grades = new HashSet<Physical_education_grades>();
            this.Russian_language_grades = new HashSet<Russian_language_grades>();
            this.Work_grades = new HashSet<Work_grades>();
        }
    
        public int id_Day { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Key_ { get; set; }
        public string Day_of_the_week { get; set; }
        public string Lesson1 { get; set; }
        public string Lesson2 { get; set; }
        public string Lesson3 { get; set; }
        public string Lesson4 { get; set; }
        public string Lesson5 { get; set; }
        public string Lesson6 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Algebra_grades> Algebra_grades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Geometry_grades> Geometry_grades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grades_Students> Grades_Students { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Literature_grades> Literature_grades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Physical_education_grades> Physical_education_grades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Russian_language_grades> Russian_language_grades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Work_grades> Work_grades { get; set; }
    }
}
